import { expect, test } from "@playwright/test";
import { cleanupNodeVisualData, NODE_VISUAL_DISTRIBUTED_PROJECT_ID, NODE_VISUAL_NAME, seedNodeVisualData } from "./helpers/devData";
import { cleanupTestProject, createTestProject } from "./unit/helpers/testProject";
import { prisma } from "../src/lib/prisma";
import { goto } from "./helpers/navigation";

// These specs mutate an isolated fixture node/project only - see the
// isolation guard (assertFixtureDatabase) seedNodeVisualData/
// cleanupNodeVisualData both call first.
test.beforeEach(async () => {
  await seedNodeVisualData();
});
test.afterEach(async () => {
  await cleanupNodeVisualData();
});
test.afterAll(async () => {
  await prisma.$disconnect();
});

// CaptureSource ids are freshly generated by every seedNodeVisualData() call
// (no fixed id to import), and CaptureSource has no nodeId column - so the
// only reliable way to find "this test run's" CaptureSource for a named
// fixture camera is through that camera's own NodeCamera row, scoped to the
// freshly-seeded node. Looking a CaptureSource up by name alone is NOT safe:
// a CaptureSource from an earlier, already-cleaned-up run can still be
// sitting in a reused fixture database under the same name.
async function captureSourceForCamera(cameraName: string) {
  const node = await prisma.plantLabNode.findUniqueOrThrow({ where: { name: NODE_VISUAL_NAME } });
  const camera = await prisma.nodeCamera.findFirstOrThrow({ where: { nodeId: node.id, name: cameraName } });
  return prisma.captureSource.findUniqueOrThrow({ where: { id: camera.captureSourceId! } });
}

test.describe("project creation with a distributed CaptureSource", () => {
  test("selecting a remote camera and sensors links them without a raw device path", async ({ page }) => {
    const wideSource = await captureSourceForCamera("Greenhouse Wide");
    const node = await prisma.plantLabNode.findUniqueOrThrow({ where: { name: NODE_VISUAL_NAME } });
    const outsideSensor = await prisma.nodeSensor.findUniqueOrThrow({ where: { nodeId_key: { nodeId: node.id, key: "greenhouse-outside" } } });
    const middleSensor = await prisma.nodeSensor.findUniqueOrThrow({ where: { nodeId_key: { nodeId: node.id, key: "greenhouse-middle" } } });

    await goto(page, "/");
    await page.getByLabel("Name").fill("Distributed Creation Test");
    await page.getByTestId(`capture-source-option-${wideSource.id}`).locator('input[type="radio"]').check();
    await page.getByTestId(`project-sensor-option-${outsideSensor.id}`).locator('input[type="checkbox"]').check();
    await page.getByTestId(`project-sensor-option-${middleSensor.id}`).locator('input[type="checkbox"]').check();

    await page.getByRole("button", { name: "Create Project" }).click();
    await page.waitForURL(/\/projects\/[^/]+$/);

    const projectId = page.url().split("/projects/")[1];
    try {
      const viewport = await prisma.projectViewport.findFirst({ where: { projectId, active: true }, include: { captureSource: true } });
      expect(viewport).not.toBeNull();
      // Bound via captureSourceId, never a raw /dev/video* path.
      expect(viewport?.captureSourceId).toBe(wideSource.id);
      const project = await prisma.project.findUniqueOrThrow({ where: { id: projectId } });
      expect(project.cameraDevice).toBeNull();

      const bindings = await prisma.projectSensorBinding.findMany({ where: { projectId, enabled: true }, include: { sensor: true } });
      expect(bindings.map((binding) => binding.sensor.key).sort()).toEqual(["greenhouse-middle", "greenhouse-outside"]);
    } finally {
      await cleanupTestProject(prisma, projectId);
    }
  });

  test("an unavailable camera is visible for context but cannot be selected", async ({ page }) => {
    const doorSource = await captureSourceForCamera("Greenhouse Door");
    await goto(page, "/");
    const doorOption = page.getByTestId(`capture-source-option-${doorSource.id}`);
    await expect(doorOption).toBeVisible();
    await expect(doorOption.locator('input[type="radio"]')).toBeDisabled();
    await expect(doorOption.getByText("Unavailable")).toBeVisible();
  });
});

test.describe("project dashboard environment", () => {
  test("shows linked sensors, a freshness badge, and populates the charts", async ({ page }) => {
    await goto(page, `/projects/${NODE_VISUAL_DISTRIBUTED_PROJECT_ID}`);
    await expect(page.getByText("Linked Sensors")).toBeVisible();
    await expect(page.getByText("Outside", { exact: true })).toBeVisible();
    await expect(page.getByText("Middle Shelf")).toBeVisible();
    await expect(page.getByText("Fresh", { exact: true }).first()).toBeVisible();
    await expect(page.locator("svg.recharts-surface").first()).toBeVisible();
  });
});

test.describe("project settings", () => {
  test("shows Capture Source mode with a link to the source, and manages sensor bindings", async ({ page }) => {
    await goto(page, `/projects/${NODE_VISUAL_DISTRIBUTED_PROJECT_ID}/settings`);

    await expect(page.getByRole("radio", { name: "Capture Source" })).toBeChecked();
    await expect(page.getByText("Capture schedule controlled by the selected Capture Source.")).toBeVisible();
    await expect(page.getByRole("link", { name: "View Capture Source" })).toBeVisible();

    const binding = await prisma.projectSensorBinding.findFirstOrThrow({ where: { label: "Middle Shelf" } });
    const middleRow = page.getByTestId(`settings-sensor-binding-${binding.id}`);
    await expect(middleRow).toBeVisible();
    await middleRow.getByRole("button", { name: "Unlink" }).click();
    await expect(page.getByText(/Unlinked \/ historical/)).toBeVisible();

    const afterUnlink = await prisma.projectSensorBinding.findUniqueOrThrow({ where: { id: binding.id } });
    expect(afterUnlink.enabled).toBe(false);
    expect(afterUnlink.unlinkedAt).not.toBeNull();

    await page.getByText(/Unlinked \/ historical/).click();
    await page.getByTestId(`settings-sensor-binding-${binding.id}`).getByRole("button", { name: "Relink" }).click();
    await expect(page.getByTestId(`settings-sensor-binding-${binding.id}`).getByRole("button", { name: "Unlink" })).toBeVisible();
    const relinked = await prisma.projectSensorBinding.findUniqueOrThrow({ where: { id: binding.id } });
    expect(relinked.enabled).toBe(true);
    expect(relinked.unlinkedAt).toBeNull();
  });
});

test.describe("photo environment card", () => {
  test("shows the nearest reading per linked sensor within the match window", async ({ page }) => {
    await goto(page, `/photos/${NODE_VISUAL_DISTRIBUTED_PROJECT_ID}-photo`);
    const card = page.getByTestId("photo-environment-card");
    await expect(card).toBeVisible();
    await expect(card.getByText("Outside", { exact: true })).toBeVisible();
    await expect(card.getByText("Middle Shelf")).toBeVisible();
    // Both linked sensors' last reading lands at the same fixture timestamp,
    // so both match the same distance - assert at least one "Matched
    // within" note rather than requiring a single unique match.
    await expect(card.getByText(/Matched within \d+ seconds/).first()).toBeVisible();
  });
});

test.describe("existing direct-local project compatibility", () => {
  test("a legacy direct-local project keeps its raw device selection editable in settings", async ({ page }) => {
    const project = await createTestProject(prisma, { name: "Legacy Direct-Local Project", cameraDevice: "/dev/video-e2e-direct" });
    try {
      await goto(page, `/projects/${project.id}/settings`);
      await expect(page.getByRole("radio", { name: "Direct Local" })).toBeChecked();
      await expect(page.locator('select[name="cameraDevice"]')).toBeVisible();
    } finally {
      await cleanupTestProject(prisma, project.id, project.localPhotoDirectory);
    }
  });
});
